versionName=3.0.0
versionCode=30
releaseTag=3.0.0
githubOwner=officerhasikhc
githubRepo=wameed
androidArtifact=Wameed-Android.apk
windowsArtifactTemplate=WameedSetup-{version}.exe
androidReleaseNotes=تحديثات هيكليه
windowsReleaseNotes=تحديثات هيكليه
sentryDsn=https://ff9d50c823a0566d8ecd6aa33a25bec7@o4511458831564800.ingest.us.sentry.io/4511514644512768
