# Generated by scripts/sync-version.ps1. Do not edit by hand.
VERSION_NAME = "2.0.4"
VERSION_CODE = 24
RELEASE_TAG = "2.0.4"
GITHUB_OWNER = "officerhasikhc"
GITHUB_REPO = "wameed"
UPDATE_JSON_URL = "https://raw.githubusercontent.com/officerhasikhc/wameed/main/update.json"
SENTRY_DSN = ""
