# Generated by scripts/sync-version.ps1. Do not edit by hand.
VERSION_NAME = "2.0.9"
VERSION_CODE = 29
RELEASE_TAG = "2.0.9"
GITHUB_OWNER = "officerhasikhc"
GITHUB_REPO = "wameed"
UPDATE_JSON_URL = "https://raw.githubusercontent.com/officerhasikhc/wameed/main/update.json"
SENTRY_DSN = "https://ff9d50c823a0566d8ecd6aa33a25bec7@o4511458831564800.ingest.us.sentry.io/4511514644512768"
