$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$versionFile = Join-Path $root "version.properties"

function Read-VersionProperties {
    param([string]$Path)
    $props = [ordered]@{}
    foreach ($rawLine in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#")) { continue }
        $idx = $line.IndexOf("=")
        if ($idx -lt 1) { continue }
        $key = $line.Substring(0, $idx).Trim()
        $value = $line.Substring($idx + 1).Trim()
        $props[$key] = $value
    }
    return $props
}

function Require-Prop {
    param($Props, [string]$Name)
    if (-not $Props.Contains($Name) -or [string]::IsNullOrWhiteSpace($Props[$Name])) {
        throw "Missing required version property: $Name"
    }
    return [string]$Props[$Name]
}

function Quote-Python {
    param([string]$Value)
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Quote-Inno {
    param([string]$Value)
    return '"' + $Value.Replace('"', '""') + '"'
}

function Version-Parts {
    param([string]$VersionName)
    $parts = @($VersionName -split "[^0-9]+" | Where-Object { $_ -ne "" } | ForEach-Object { [int]$_ })
    while ($parts.Count -lt 4) { $parts += 0 }
    return $parts[0..3]
}

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

$props = Read-VersionProperties $versionFile
$versionName = Require-Prop $props "versionName"
$versionCode = [int](Require-Prop $props "versionCode")
$releaseTag = Require-Prop $props "releaseTag"
$owner = Require-Prop $props "githubOwner"
$repo = Require-Prop $props "githubRepo"
$androidArtifact = Require-Prop $props "androidArtifact"
$windowsArtifact = (Require-Prop $props "windowsArtifactTemplate").Replace("{version}", $versionName)
$androidNotes = [string]$props["androidReleaseNotes"]
$windowsNotes = [string]$props["windowsReleaseNotes"]
$sentryDsn = [string]$props["sentryDsn"]

$releaseBase = "https://github.com/$owner/$repo/releases/download/$releaseTag"
$updateJson = [ordered]@{
    android = [ordered]@{
        versionCode = $versionCode
        versionName = $versionName
        updateUrl = "$releaseBase/$androidArtifact"
        isForceUpdate = $false
        releaseNotes = $androidNotes
    }
    windows = [ordered]@{
        version = $versionName
        updateUrl = "$releaseBase/$windowsArtifact"
        releaseNotes = $windowsNotes
    }
}

$jsonPath = Join-Path $root "update.json"
Write-Utf8NoBom $jsonPath (($updateJson | ConvertTo-Json -Depth 5) + "`r`n")

$pyPath = Join-Path $root "windows-receiver\src\wameed_version.py"
$py = @(
    "# Generated by scripts/sync-version.ps1. Do not edit by hand.",
    "VERSION_NAME = $(Quote-Python $versionName)",
    "VERSION_CODE = $versionCode",
    "RELEASE_TAG = $(Quote-Python $releaseTag)",
    "GITHUB_OWNER = $(Quote-Python $owner)",
    "GITHUB_REPO = $(Quote-Python $repo)",
    "UPDATE_JSON_URL = $(Quote-Python "https://raw.githubusercontent.com/$owner/$repo/main/update.json")",
    "SENTRY_DSN = $(Quote-Python $sentryDsn)"
)
Write-Utf8NoBom $pyPath (($py -join "`r`n") + "`r`n")

$innoVersionPath = Join-Path $root "windows-receiver\installer\version.iss"
$innoContent = (@(
    "; Generated by scripts/sync-version.ps1. Do not edit by hand.",
    "#define AppVersion $(Quote-Inno $versionName)"
) -join "`r`n") + "`r`n"
Write-Utf8NoBom $innoVersionPath $innoContent

$v = Version-Parts $versionName
$versionInfoPath = Join-Path $root "windows-receiver\version_info.txt"
$versionInfo = @"
# Generated by scripts/sync-version.ps1. Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($($v[0]), $($v[1]), $($v[2]), $($v[3])),
    prodvers=($($v[0]), $($v[1]), $($v[2]), $($v[3])),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Wameed Project'),
          StringStruct('FileDescription', 'Wameed desktop receiver'),
          StringStruct('FileVersion', '$versionName'),
          StringStruct('InternalName', 'Wameed'),
          StringStruct('OriginalFilename', 'Wameed.exe'),
          StringStruct('ProductName', 'Wameed'),
          StringStruct('ProductVersion', '$versionName')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"@
Write-Utf8NoBom $versionInfoPath $versionInfo

Write-Host "Version sync complete: $versionName ($versionCode)"
